/**
 * WikiFab data transformer
 * Transforms WikiFab tutorial data to ProductInstance and Process objects
 */

import type { InputInstance } from '@trace.market/types';
import type { WikiFabTutorial } from '../api/WikiFabClient';
import type {
  ProductInstanceWithSources,
  ProcessInstanceWithSources,
  TransformResult,
} from '../../types/decomposition';
import { CONFIDENCE_PENALTIES } from '../../config/apiConfig';

/**
 * WikiFab transformer
 */
export class WikiFabTransformer {
  /**
   * Transform WikiFab tutorial to ProductInstance
   */
  transform(
    tutorial: WikiFabTutorial
  ): TransformResult<ProductInstanceWithSources> {
    const errors: string[] = [];
    const warnings: string[] = [];

    // Validate required fields
    if (!tutorial.title) {
      errors.push('Missing tutorial title');
    }

    // Calculate confidence score
    const confidence = this.calculateConfidence(tutorial);

    // Build ProductInstance
    const productInstance: ProductInstanceWithSources = {
      type: tutorial.title,
      category: 'general', // DIY products

      // Transform materials to inputs
      ...(tutorial.materials &&
        tutorial.materials.length > 0 && {
          inputs: this.transformMaterials(tutorial.materials),
        }),

      // Add external source metadata
      externalSources: [
        {
          source: 'WikiFab',
          id: tutorial.pageId.toString(),
          url: tutorial.url,
          confidence,
          fetchedAt: new Date().toISOString(),
        },
      ],

      // Add decomposition metadata
      decompositionMetadata: {
        autoGenerated: true,
        manuallyEdited: false,
        depth: 0,
        truncated: false,
      },

      // Store WikiFab-specific data
      ...(tutorial.description && { description: tutorial.description }),
      ...(tutorial.difficulty && { difficulty: tutorial.difficulty }),
      ...(tutorial.duration && { duration: tutorial.duration }),
      ...(tutorial.cost && { estimatedCost: tutorial.cost }),
      ...(tutorial.license && { license: tutorial.license }),
      ...(tutorial.author && { author: tutorial.author }),
    };

    // Add warnings
    if (!tutorial.materials || tutorial.materials.length === 0) {
      warnings.push('No materials list available');
    }

    if (!tutorial.steps || tutorial.steps.length === 0) {
      warnings.push('No step-by-step instructions available');
    }

    return {
      data: productInstance,
      confidence,
      errors: errors.length > 0 ? errors : undefined,
      warnings: warnings.length > 0 ? warnings : undefined,
    };
  }

  /**
   * Transform materials to InputInstance array
   */
  private transformMaterials(
    materials: NonNullable<WikiFabTutorial['materials']>
  ): InputInstance[] {
    return materials.map((material, index) => {
      const instance = {
        type: material.name || `Material ${index}`,
        category: 'general',
        description: material.notes || '',
        quantity: 1,
        bio: false,
        grade: 'standard',
        size: 'standard',
      };

      const inputInstance: any = {
        type: 'local',
        quantity: material.quantity ? parseFloat(material.quantity) || 1 : 1,
        instance: instance as any,
      };

      return inputInstance as InputInstance;
    });
  }

  /**
   * Extract manufacturing processes from tutorial steps
   */
  extractProcesses(tutorial: WikiFabTutorial): ProcessInstanceWithSources[] {
    if (!tutorial.steps || tutorial.steps.length === 0) {
      return [];
    }

    return tutorial.steps.map((step, index) => {
      const process: ProcessInstanceWithSources = {
        type: 'Manufacturing Step',
        category: 'manufacturing',

        description: `Step ${step.number}: ${step.title}\n\n${step.description}`,

        // Link steps sequentially
        ...(index > 0 && {
          inputInstances: [
            {
              identifier: `step-${index}-output`,
              category: 'general',
              name: `Output from Step ${index}`,
            },
          ],
        }),

        // External source metadata
        externalSources: [
          {
            source: 'WikiFab',
            id: `${tutorial.pageId}-step-${step.number}`,
            url: `${tutorial.url}#step-${step.number}`,
            confidence: this.calculateConfidence(tutorial),
            fetchedAt: new Date().toISOString(),
          },
        ],

        decompositionMetadata: {
          autoGenerated: true,
          manuallyEdited: false,
          depth: 0,
          truncated: false,
        },

        ...(step.imageUrl && { imageUrl: step.imageUrl }),
      };

      return process;
    });
  }

  /**
   * Calculate confidence score
   */
  calculateConfidence(tutorial: WikiFabTutorial): number {
    let confidence = 1.0;

    // Required fields
    if (!tutorial.title) {
      confidence -= CONFIDENCE_PENALTIES.missingRequiredField;
    }

    // Important optional fields
    if (!tutorial.steps || tutorial.steps.length === 0) {
      confidence -= CONFIDENCE_PENALTIES.missingOptionalField * 2; // Steps are very important
    }

    if (!tutorial.materials || tutorial.materials.length === 0) {
      confidence -= CONFIDENCE_PENALTIES.missingOptionalField * 2; // Materials are very important
    }

    if (!tutorial.description) {
      confidence -= CONFIDENCE_PENALTIES.missingOptionalField;
    }

    if (!tutorial.imageUrl) {
      confidence -= CONFIDENCE_PENALTIES.missingOptionalField;
    }

    // Completeness based on available metadata
    let metadataCount = 0;
    const totalMetadata = 5;

    if (tutorial.difficulty) metadataCount++;
    if (tutorial.duration) metadataCount++;
    if (tutorial.cost) metadataCount++;
    if (tutorial.license) metadataCount++;
    if (tutorial.author) metadataCount++;

    const metadataCompleteness = metadataCount / totalMetadata;
    confidence *= 0.7 + 0.3 * metadataCompleteness; // 70% base + 30% from metadata

    // Ensure confidence is between 0.1 and 1.0
    return Math.max(0.1, Math.min(1.0, confidence));
  }
}

/**
 * Singleton instance
 */
export const wikiFabTransformer = new WikiFabTransformer();
